project:
  type: book

book:
  title: "LLM Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/llm-notes
  site-url: https://llm-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - references.qmd
    - part: "OpenAI"
      chapters: 
        - "content/openai/openai-vision.ipynb"
        - "content/openai/openai-dataext-etl-1.ipynb"
        - "content/openai/openai-dataext-etl-2.ipynb"
    - part: "Regex"
      chapters: 
        - "regex/censor-text.ipynb"
    - part: "Parsing"
      chapters: 
        - "parse/pymupdf.ipynb"

bibliography: references.bib

format:
  html:
    theme: zephyrs

execute:
  freeze: auto